# Generated by Django 6.0.1 on 2026-02-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_course'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table=None,
        ),
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
