# Generated by Django 6.0.1 on 2026-02-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_course_table_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
