# Generated by Django 6.0.1 on 2026-02-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(),
        ),
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
