# Generated by Django 6.0.1 on 2026-02-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_product_alter_student_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
